swagger: "2.0"
info:
  version: 1.0.0
  title: Health Measurements
  license:
    name: MIT
host: https://us-central1-health-monitoring-c4a62.cloudfunctions.net/app
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /measurements:
    get:
      summary: Get Measurements for monitoring the health of a patient in a specific period
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: The identifier of the user 
        - in: query
          name: startDate
          schema:
            type: string
            format: full-date
          description: The start date 
        - in: query
          name: endDate
          schema:
            type: string
            format: full-date # ISO8601 full-date YYYY-MM-DD
          description: The end date 
      responses:
        "200":
          description: A JSON object containing measurements as keys along with their values
          content:
            application/json:
              schema:
                type: object
                properties:
                  weight:
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
                  temperature:
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
                  pain:
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
                  medication:
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
                  symptoms: 
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
                  diarrhea:
                    type: object
                    properties:
                      data:
                        type: object
                        description: A hashmap with date as a key and the data related to that date as the value.
                      status:
                        type: object
                        proporties:
                          message:
                            type: string
